// 10 default format templates from the AI KOL/KOC spec
import type { FormatTemplateData } from "./format-template-types";

export const DEFAULT_FORMAT_TEMPLATES: FormatTemplateData[] = [
  {
    slug: "review",
    name: "Review",
    description: "Review sản phẩm trực tiếp, chân thật, có bằng chứng",
    goal: "Trust + soft sell",
    hookTemplate: "[Tình huống/câu hỏi gây tò mò] + teaser kết quả",
    bodyTemplate: "Unbox → First impression → Test thực tế → So sánh kỳ vọng vs thực tế → Kết luận",
    proofTemplate: "Close-up texture/kết quả, before/after, so sánh với SP khác (không nêu tên)",
    ctaTemplate: "Link ở bio / Giỏ hàng màu vàng + urgency nhẹ",
    exampleScript: "\"Mình mua cái này vì thấy 50K lượt bán... mà liệu có đáng không?\" → Unbox, test 3 ngày → \"Kết quả: [kết quả]. Link ở bio nhé!\"",
  },
  {
    slug: "myth-bust",
    name: "Myth-bust",
    description: "Đập tan hiểu lầm phổ biến, tạo controversy nhẹ",
    goal: "Engagement + authority",
    hookTemplate: "\"[Hiểu lầm phổ biến]\" — SAI! / Thật ra...",
    bodyTemplate: "Nêu myth → Giải thích tại sao sai → Đưa bằng chứng/test → Sự thật → SP giải quyết",
    proofTemplate: "Data, test trực tiếp, chuyên gia nói, so sánh visual",
    ctaTemplate: "\"Biết rồi thì đừng sai nữa\" + link SP",
    exampleScript: "\"Nhiều người nghĩ [myth]... MÀ SAI!\" → Test chứng minh → \"Sự thật là...\" → SP → CTA",
  },
  {
    slug: "a-vs-b",
    name: "A vs B",
    description: "So sánh 2 sản phẩm/cách/trạng thái, tạo debate",
    goal: "Engagement + decision help",
    hookTemplate: "[SP A] hay [SP B]? Test thử xem!",
    bodyTemplate: "Giới thiệu 2 lựa chọn → Test song song → So sánh từng tiêu chí → Verdict",
    proofTemplate: "Split screen, bảng so sánh, close-up chi tiết",
    ctaTemplate: "\"Team nào? Comment đi\" + link SP winner",
    exampleScript: "\"[A] 200K vs [B] 500K — đắt gấp đôi có tốt gấp đôi?\" → Test → \"Winner là...\" → CTA",
  },
  {
    slug: "checklist",
    name: "Checklist",
    description: "Dạng list tips/bước, dễ save, educational",
    goal: "Save + authority",
    hookTemplate: "[Số] điều/bước/sai lầm [về chủ đề] — bạn biết mấy cái?",
    bodyTemplate: "Điểm 1 → Điểm 2 → ... → Điểm cuối (surprise/twist) → SP liên quan",
    proofTemplate: "Text overlay rõ ràng mỗi điểm, visual minh họa",
    ctaTemplate: "\"Save lại kẻo quên\" + link SP nếu liên quan",
    exampleScript: "\"5 sai lầm khi [topic]\" → Từng sai lầm + cách sửa → \"Cái số 4 nhiều người mắc nhất\" → CTA",
  },
  {
    slug: "story",
    name: "Story",
    description: "Kể chuyện cá nhân gắn với SP, tạo cảm xúc",
    goal: "Trust + emotional connection",
    hookTemplate: "Chuyện này mình chưa kể ai... / Ngày đó mình...",
    bodyTemplate: "Setup (vấn đề) → Conflict (thử nhiều cách) → Resolution (tìm ra SP) → Kết quả",
    proofTemplate: "Ảnh/video quá khứ, before/after cá nhân, cảm xúc thật",
    ctaTemplate: "\"Nếu bạn cũng gặp vấn đề này...\" + link",
    exampleScript: "\"Hồi trước mình [vấn đề]...\" → Thử nhiều cách thất bại → Tìm ra SP → \"Bây giờ thì...\" → CTA",
  },
  {
    slug: "test",
    name: "Test thực tế",
    description: "Test SP trong điều kiện thực tế, khắc nghiệt",
    goal: "Trust + proof",
    hookTemplate: "Test [SP] trong [điều kiện khắc nghiệt] — liệu có sống sót?",
    bodyTemplate: "Giới thiệu SP + test → Thiết lập điều kiện → Test step by step → Kết quả bất ngờ",
    proofTemplate: "Video liên tục không cắt, close-up kết quả, đo lường cụ thể",
    ctaTemplate: "\"Kết quả ngoài mong đợi\" + link SP",
    exampleScript: "\"Test [SP] 24h liên tục\" → Setup → Theo dõi từng giờ → \"Kết quả: [bất ngờ]\" → CTA",
  },
  {
    slug: "react",
    name: "React/Reaction",
    description: "Phản ứng với trend, SP mới, claim gây tranh cãi",
    goal: "Engagement + reach",
    hookTemplate: "Mọi người đang nói [trend/claim] — mình nghĩ...",
    bodyTemplate: "Show trend/clip → Phản ứng ban đầu → Phân tích → Kết luận cá nhân",
    proofTemplate: "Screen record trend, facial reactions, data nếu có",
    ctaTemplate: "\"Bạn nghĩ sao? Comment đi\" + link nếu liên quan",
    exampleScript: "\"Clip này viral 10M views nói [claim]\" → Watch → \"Hmm...\" → Phân tích → \"Sự thật là...\"",
  },
  {
    slug: "mini-drama",
    name: "Mini Drama",
    description: "Tiểu phẩm ngắn, hài hước, SP xuất hiện tự nhiên",
    goal: "Entertainment + brand recall",
    hookTemplate: "POV: [tình huống hài/relate] / Khi bạn [scenario]...",
    bodyTemplate: "Setup tình huống → Complication → SP xuất hiện giải quyết → Punchline",
    proofTemplate: "Acting, facial expressions, timing comedic, SP tự nhiên trong scene",
    ctaTemplate: "\"Diễn xuất 10 điểm\" style — CTA nhẹ cuối",
    exampleScript: "\"POV: bạn mua [SP rẻ] vs [SP đắt]\" → Drama diễn xuất → Twist cuối → CTA nhẹ",
  },
  {
    slug: "series-challenge",
    name: "Series Challenge",
    description: "Thử thách kéo dài nhiều tập, tạo habit xem",
    goal: "Retention + follower growth",
    hookTemplate: "Ngày [X]/30 thử thách [challenge] — hôm nay...",
    bodyTemplate: "Recap → Thử thách hôm nay → Kết quả → Teaser ngày mai",
    proofTemplate: "Progress tracking visible, before/after daily, consistency proof",
    ctaTemplate: "\"Follow để xem ngày mai\" + link SP nếu dùng trong challenge",
    exampleScript: "\"Ngày 7/30 dùng [SP] mỗi ngày\" → Update → \"Kết quả hôm nay: [kết quả]\" → \"Ngày mai mình sẽ...\"",
  },
  {
    slug: "deal-breakdown",
    name: "Deal Breakdown",
    description: "Phân tích deal/giá, giúp người xem quyết định mua",
    goal: "Conversion + value",
    hookTemplate: "[SP] đang sale [X]% — đáng mua không? Tính xem...",
    bodyTemplate: "Show deal → Phân tích giá gốc vs sale → So sánh alternatives → Verdict đáng hay không",
    proofTemplate: "Screenshot giá, bảng so sánh, tính toán cụ thể",
    ctaTemplate: "\"Deal này [đáng/không đáng]\" + link mua ngay nếu đáng",
    exampleScript: "\"[SP] sale 50% chỉ còn [giá]\" → Tính: giá thường bao nhiêu, SP tương tự giá nào → \"Verdict: [đáng]\" → CTA urgency",
  },
];
